from pathlib import Path

PROJECT_ROOT = Path(__file__).resolve().parents[2]
DATA_DIR = PROJECT_ROOT / 'data'
RAW_DATA_DIR = DATA_DIR / 'raw'
OLIST_DATA_DIR = RAW_DATA_DIR / 'olist'

REPORTS_DIR = PROJECT_ROOT / 'reports'
RAW_INVENTORY_REPORT_DIR = REPORTS_DIR / 'raw_inventory'
RAW_PROFILE_REPORT_DIR = REPORTS_DIR / 'raw_profile'
RAW_QUALITY_REPORT_DIR = REPORTS_DIR / 'data_quality'


PROCESSED_DATA_DIR = DATA_DIR / 'processed'
OLIST_CLEAN_DATA_DIR = PROCESSED_DATA_DIR / 'olist_clean'

CLEANING_REPORT_DIR = REPORTS_DIR / 'cleaning'
CLEANING_VALIDATION_REPORT_DIR = REPORTS_DIR / 'cleaning_validation'

SUPPLIER_RAW_DATA_DIR = RAW_DATA_DIR / 'suppliers'
SUPPLIER_CLEAN_DATA_DIR = PROCESSED_DATA_DIR  / 'supplier_clean'
SUPPLIER_INVENTORY_REPORT_DIR = REPORTS_DIR / 'supplier_inventory'
SUPPLIER_PROFILE_REPORT_DIR = REPORTS_DIR / 'supplier_profile'
SUPPLIER_QUALITY_REPORT_DIR = REPORTS_DIR / 'supplier_quality'
SUPPLIER_CLEANING_REPORT = CLEANING_REPORT_DIR / 'supplier_cleaning'
SUPPLIER_CLEANING_VALIDATION_REPORT_DIR  = REPORTS_DIR / 'supplier_cleaning_validation'

BR_HOLIDAYS_RAW_DATA_DIR = RAW_DATA_DIR / 'br_holidays'
BR_HOLIDAYS_CLEAN_DATA_DIR = PROCESSED_DATA_DIR  / 'br_holidays_clean'
BR_HOLIDAYS_INVENTORY_REPORT_DIR = REPORTS_DIR / 'br_holidays_inventory'
BR_HOLIDAYS_PROFILE_REPORT_DIR = REPORTS_DIR / 'br_holidays_profile'
BR_HOLIDAYS_QUALITY_REPORT_DIR = REPORTS_DIR / 'br_holidays_quality'
BR_HOLIDAYS_CLEANING_REPORT_DIR = CLEANING_REPORT_DIR / 'br_holidays_cleaning'
BR_HOLIDAYS_CLEANING_VALIDATION_REPORT_DIR  = REPORTS_DIR / 'br_holidays_cleaning_validation'

POSTGRES_VALIDATION_REPORT_DIR = REPORTS_DIR / "postgres_validation"

DEFAULT_CHUNK_SIZE = 100_000
DEFAULT_SAMPLE_VALUES_LIMIT = 5
NAGER_PUBLIC_HOLIDAYS_URL = ("https://date.nager.at/api/v3/PublicHolidays/{year}/{country_code}")