from pathlib import Path

PROJECT_ROOT = Path(__file__).resolve().parents[2]
DATA_DIR = PROJECT_ROOT / 'data'
RAW_DATA_DIR = DATA_DIR / 'raw'
OLIST_DATA_DIR = RAW_DATA_DIR / 'olist'

REPORTS_DIR = PROJECT_ROOT / 'reports'
RAW_INVENTORY_REPORT_DIR = REPORTS_DIR / 'raw_inventory'
RAW_PROFILE_REPORT_DIR = REPORTS_DIR / 'raw_profile'
RAW_QUALITY_REPORT_DIR = REPORTS_DIR / 'data_quality'
CLEANING_REPORT_DIR = REPORTS_DIR / 'cleaning'

PROCESSED_DATA_DIR = DATA_DIR / 'processed'
OLIST_CLEAN_DATA_DIR = PROCESSED_DATA_DIR / 'olist_clean'

CLEANING_VALIDATION_REPORT_DIR = REPORTS_DIR / 'cleaning_validation'

DEFAULT_CHUNK_SIZE = 100_000
DEAFULT_SAMPLE_VALUES_LIMIT = 5
